# Working #######
#version: 0.0
#os: linux
#files:
#  - source: /
#    destination: /opt/tomcat/webapps/
#hooks:
#  BeforeInstall:
#    - location: scripts/stop_tomcat.sh
#      timeout: 180
#      runas: root
#  AfterInstall:
#    - location: scripts/start_tomcat.sh
#      timeout: 180
#      runas: root
###########
version: 0.0
os: linux
files:
  - source: /
    destination: /opt/tomcat/webapps/
hooks:
  BeforeInstall:
    - location: scripts/stop_tomcat.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/start_tomcat.sh
      timeout: 60
      runas: root
  #ApplicationStart:
  #  - location: scripts/deploy_war.sh
  #    timeout: 300
  #    runas: root
  #ValidateService:
  #  - location: scripts/validate.sh
  #    timeout: 20
  #    runas: root      
