version: 0.0
os: linux
files:
  - source: /
    destination: /opt/tomcat/webapps/
hooks:
  BeforeInstall:
    - location: scripts/stop_tomcat.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/start_tomcat.sh
      timeout: 180
      runas: root
