# Working #######
#version: 0.0
#os: linux
#files:
#  - source: /gs-spring-boot-0.1.0.jar
#    destination: /opt/tomcat/webapps/
#hooks:
#  BeforeInstall:
#    - location: scripts/stop_tomcat.sh
#      timeout: 180
#      runas: root
#  AfterInstall:
#    - location: scripts/start_tomcat.sh
#      timeout: 180
#      runas: root
###########
version: 0.0
os: linux
files:
  - source: /
    destination: /opt/myapp/
hooks:
  BeforeInstall:
    - location: scripts/stop_tomcat.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/start_tomcat.sh
      timeout: 180
      runas: root
  applicationStart:
    - location: scripts/deploy_war.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate.sh
      timeout: 20
      runas: root      
