version: 0.0
os: linux
files:
  - source: /
    destination: /opt/tomcat/webapps/
hooks:
  BeforeInstall:
    - location: scripts/stop-tomcat.sh
      timeout: 180
      runas: tomcat
  AfterInstall:
    - location: scripts/start-tomcat.sh
      timeout: 180
      runas: tomcat
        
