version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - yum install -y maven
  build:
    commands:
      - mvn install
artifacts:
  files:
      - '**/*'
  discard-paths: yes   
