version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - yum install -y maven
  build:
    commands:
      - mvn package
artifacts:
  files:
    - target/gs-*.jar
    - appspec.yml
  discard-paths: yes
