version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - yum install -y maven
  build:
    commands:
      - mvn package
      - mv target/gs-spring-boot-0.1.0.jar gs-spring-boot-0.1.0.jar  
artifacts:
  files:
      - gs-spring-boot-0.1.0.jar
      - appspec.yml
      - 'scripts/*'  
  discard-paths: yes
